[package]
name = "net-scan"
version = "1.17.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[dependencies]
threadpool = "1.8.1"
num_cpus = "1.16.0"
ping = "0.5.1"
format = "0.2.4"